version: '3.5'

services:

  database:
    container_name: osem-db
    image: postgres:11
    volumes:
      - pg-data:/var/lib/postgresql/data

  web:
    container_name: osem-web
    build:
      context: .
      args:
        CONTAINER_USERID: 1000
    command: /osem/bin/osem-init.sh
    depends_on:
      - database
    ports:
      - 3000:3000
    volumes:
      - .:/osem

volumes:
  pg-data:
